### ISSUE TITLE
Sbtid issue

### ISSUE THREAD

**Issue by xvolte** [HugoPoi/9boxtv#3]
Bonjour,

J’ai une sbt7 de sfr. Pouvez vous me dire ou se situe le stbid et le format de celui ci?
Sur l etiquette il n y a pas ecrit de stbid. 

Merci par avance

**Comment by HugoPoi** [comment]
De mémoire il y en a pas vraiment besoin mais si tu veux l'obtenir tu peux faire un MITM avec Kali par exemple.
Normalement transmettre un faux permet quand d'obtenir la liste des chaînes.
