### ISSUE TITLE
Box plus (NB6VAC)

### ISSUE THREAD

**Issue by oliv615** [HugoPoi/9boxtv#4]
Bonjour,

Merci pour ce script. Y a t-il une possibilité de l'adapter pour l'utiliser avec la box "plus (NB6VAC)" de SFR ? Le décodeur Tv est le stb7.

Merci encore.
Olivier.

**Comment by HugoPoi** [comment]
Je vais checker mais ça fait longtemps que je n'ai pas vérifié que l'API SFR était toujours la même. Normalement peu importe la version de la box l'api est la même pour tous les clients. Donc tu dois pouvoir utiliser le script curl pour récupérer le fichier de config XML.

**Comment by oliv615** [comment]
Merci beaucoup pour votre aide et votre temps.
J'avais suivi un tuto mais qui doit être trop ancien. Dans vos instructions je n'ai pas compris ce qu'il faut faire pour ces deux points : 
2. Effectuer une première requête qui renvoi le `nonce` dans les headers HTTP
3. Ensuite refaire la même requête avec le `nonce` injecté.

Merci encore.

**Comment by oliv615** [comment]
Voila ce que j'ai fait :
- J'ai décommenté et édité la ligne 6 en indiquant le S/N de ma box (pas de stbid)
- J'ai lancé la commande curl -v --config get_config.curl -o channels_list.xml
- Je récupère le nonce qui s'affiche dans la réponse et le met dans la ligne 7
- Je commente a nouveau la ligne 6 et relance la commande
Mais le fichier channel_list.xml reste vide.

**Comment by HugoPoi** [comment]
J'ai vérifié et je confirme il y a pas besoin d'avoir des ID valide pour obtenir la config. J'ai édité les config curl et maintenant ça marche en l'état :smiley: 
J'en ai profité pour update la liste des chaines

**Comment by oliv615** [comment]
Super, merci beaucoup d'avoir pris le temps de m'aider.

**Comment by HugoPoi** [comment]
Si c'est bon pour vous, vous pouvez fermer le ticket ;-)
